services:
  mysql:
    image: mysql:8.0.43
    container_name: mysql-8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sincordb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      TZ: "America/Sao_Paulo"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Opcional: scripts .sql ou .sh em ./init serão executados na primeira inicialização
#      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db_data:


#services:
#  mysql:
#    image: mysql:8.0.43
#    container_name: mysql-sincor2
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword   # troque para uma senha forte
#      MYSQL_DATABASE: sincor          # opcional: cria um banco inicial
#      MYSQL_USER: admin             # opcional: cria usuário
#      MYSQL_PASSWORD: minha_senha         # opcional: senha do usuário
#    volumes:
#      - mysql_data:/var/lib/mysql
##      - ./my.conf:/etc/mysql/conf.d/my.conf  # configuração customizada
#    ports:
#      - "3306:3306"
#
#volumes:
#  mysql_data:
#    driver: local
