CREATE TABLE DISTRITO_JUDICIARIO
(
    ID         BIGINT       NOT NULL AUTO_INCREMENT,
    NOME       VARCHAR(200) NOT NULL,
    ID_COMARCA BIGINT       NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT DIST_JUD_COMARCA_FK FOREIGN KEY (ID_COMARCA) REFERENCES COMARCA (ID)
) ENGINE=InnoDB;

CREATE INDEX DISTRITO_NOME_UK ON DISTRITO_JUDICIARIO (NOME ASC);
