CREATE TABLE ESTADO
(
    ID   BIGINT       NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    SIGLA   VARCHAR(2)   NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE INDEX ESTADO_NOME_UK ON ESTADO (NOME ASC);
CREATE INDEX ESTADO_SIGLA_UK ON ESTADO (SIGLA ASC);


