INSERT INTO SUB_DISTRITO (ID, NOME, ID_DISTRITO) VALUES (1, 'Canasvieiras', 13);

INSERT INTO SUB_DISTRITO (ID, NOME, ID_DISTRITO) VALUES (2, 'Ingleses', 13);

ALTER TABLE SUB_DISTRITO AUTO_INCREMENT = 3;
