-- MySQL 8.0
CREATE TABLE SUB_DISTRITO
(
    ID             BIGINT       NOT NULL AUTO_INCREMENT,
    NOME           VARCHAR(200) NOT NULL,
    ID_DISTRITO    BIGINT       NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT SUB_DIST_DIST_FK FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO_JUDICIARIO (ID)
) ENGINE=InnoDB;

CREATE INDEX SUB_DISTRITO_NOME_IDX ON SUB_DISTRITO (NOME ASC);
CREATE INDEX SUB_DISTRITO_DIST_IDX ON SUB_DISTRITO (ID_DISTRITO ASC);
