ALTER TABLE ORGAO
    ADD COLUMN ID_SUB_DISTRITO BIGINT NULL AFTER ID_DISTRITO;

ALTER TABLE ORGAO
    ADD CONSTRAINT ORGAO_SUB_DIST_FK
        FOREIGN KEY (ID_SUB_DISTRITO) REFERENCES SUB_DISTRITO (ID);

CREATE INDEX ORGAO_SUB_DISTRITO_IDX ON ORGAO (ID_SUB_DISTRITO ASC);
