-- MySQL 8.0

CREATE TABLE COMARCA
(
    ID        BIGINT       NOT NULL AUTO_INCREMENT,
    NOME      VARCHAR(200) NOT NULL,
    ENTRANCIA INT          NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE INDEX COMARCA_NOME_UK ON COMARCA (NOME ASC);
