-- MySQL 8.0
CREATE TABLE ORGAO
(
    ID            BIGINT       NOT NULL AUTO_INCREMENT,
    NOME          VARCHAR(300) NOT NULL,
    ID_DISTRITO   BIGINT       NOT NULL,
    CNPJ          BIGINT       NOT NULL,
    ATIVO         BOOLEAN      NOT NULL DEFAULT TRUE,
    AREA_CARTORIO CHAR(1)      NOT NULL COMMENT 'C-comunica; E-extra judicial; J-judicial; F-serventias de outros estados; G-empresas',
    CNS           INT          NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT ORGAO_DIST_FK FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO_JUDICIARIO (ID),
    CONSTRAINT ORGAO_CNS_UK UNIQUE (CNS),
    CONSTRAINT ORGAO_CNPJ_UK UNIQUE (CNPJ),
    CONSTRAINT ORGAO_AREA_CARTORIO_CK CHECK (AREA_CARTORIO IN ('C', 'E', 'J', 'F', 'G')),
    CONSTRAINT ORGAO_CNPJ_LEN_CK CHECK (CNPJ BETWEEN 10000000000000 AND 99999999999999)
) ENGINE=InnoDB;

CREATE INDEX ORGAO_NOME_IDX ON ORGAO (NOME ASC);
CREATE INDEX ORGAO_DISTRITO_IDX ON ORGAO (ID_DISTRITO ASC);
